// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pelkxvldokkmdesbdyek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbGt4dmxkb2trbWRlc2JkeWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTgxNzEsImV4cCI6MjA2ODMzNDE3MX0.bHvSloFvD3FyUTG6HcPXlV4EXEDaa8pW18ZAwriYmEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});